terrain: "BlockRight"
run_derivative_test: false
plot_trajectory: false
optimize_phase_durations: false
play_initialization: false
init_state_from_file: true  # 'true' if initial_pose for base is read from this file, 'false' if it is set by the current anymal state

# Possible gaits: 
# 0 (C0 - overlap-walk)
# 1 (C1 - running trot)
# 2 (C2 - running pace) 
# 3 (C3 - bounding) 
# 4 (C4 - gallop) 
# 5 (C5 - static-walk) 
# 6 (C6 - overlap-walk)
# 7 (lateral troting)
# 8 (driving)
# 9 (BlockCross - gallop) => works well for 3 polynomials in the swing phase
# 10 (BlockBound - bounding) 
# 11 (GapCross - gallop) => works well for 3 polynomials in the swing phase
# 12 (GapBound - bounding)  
# 13 (BlockRight)

constrain_final_z_base: false
shift_initialization: false
n_polys_in_swing_phase: 2
min_distance_above_terrain: 0.0 #0.08

Flat:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.48
   
  final_pose: 
    x: 2.0 
    y: 0.0
    z: 0.48

  final_yaw_angle: 0.0 #1.57079632679
  total_time: 2.0
  gait: 4
  use_non_holonomic_constraint: true
  limit_base_angles: true
  max_wheels_acc_z: 100.0

Gap:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.65
   
  final_pose: 
    x: 1.5
    y: 0.0
    z: 0.65

  final_yaw_angle: 0.0
  total_time: 2.0
  gait: 11 #12
  use_non_holonomic_constraint: false
  limit_base_angles: true # generates smoother motions, not mandatory

Block:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.45
   
  final_pose: 
    x: 1.5 
    y: 0.0
    z: 0.65

  final_yaw_angle: 0.0
  total_time: 2.0
  gait: 9 #10
  use_non_holonomic_constraint: false
  limit_base_angles: false

BlockRight:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.45
   
  final_pose: 
    x: 1.5 
    y: 0.0
    z: 0.45

  final_yaw_angle: 0.0
  total_time: 2.0
  gait: 13
  use_non_holonomic_constraint: false
  limit_base_angles: false


