run_derivative_test: false

Flat:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 4.0
    y: 0.0
    z: 0.5

  total_time: 4.0

Block:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 2.0
    y: 0.0
    z: 0.5

  total_time: 4.0

Stairs:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 2.0
    y: 0.0
    z: 0.5

  total_time: 4.0

Gap:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 2.0
    y: 0.0
    z: 0.5

  total_time: 4.0

Slope:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 4.0
    y: 0.0
    z: 0.5

  total_time: 8.0

Step:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.4
   
  final_pose: 
    x: 1.7
    y: 0.0
    z: 0.6

  total_time: 5.0

SlopePlat:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 6.0
    y: 0.0
    z: 0.7

  total_time: 6.0

SineLowFreq:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.7
   
  final_pose: 
    x: 2.0
    y: 0.0
    z: 0.7

  total_time: 4.0

SineHighFreq:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 2.0
    y: 0.0
    z: 0.5

  total_time: 4.0







