run_derivative_test: true

Step:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 2.0
    y: 0.0
    z: 0.7

  total_time: 5.0

SlopePlat:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 6.0
    y: 0.0
    z: 0.7

  total_time: 6.0

Flat:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 0.3
    y: 0.0
    z: 0.5

  total_time: 0.4

SineLowFreq:
  initial_pose:
    x: 1.0
    y: 0.0
    z: 0.7
   
  final_pose: 
    x: 1.1
    y: 0.0
    z: 0.7

  total_time: 0.2

SineHighFreq:
  initial_pose:
    x: 1.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 1.3
    y: 0.0
    z: 0.5

  total_time: 0.4

Slope:
  initial_pose:
    x: 1.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 1.3
    y: 0.0
    z: 0.5

  total_time: 0.4

Gap:
  initial_pose:
    x: 1.0
    y: 0.0
    z: 0.7
   
  final_pose: 
    x: 1.1
    y: 0.0
    z: 0.7

  total_time: 0.2

