run_derivative_test: false

Flat:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.4
   
  final_pose: 
    x: 4.0
    y: 0.0
    z: 0.4

  total_time: 4.0
  use_wheels_motion_constraint: false
  traction_limit: 30.0

Step:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 2.0
    y: 0.0
    z: 0.7

  total_time: 4.0 #5.0
  use_wheels_motion_constraint: false
  traction_limit: 300.0 #10.0

TwoStep:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 3.0
    y: 0.0
    z: 0.5

  total_time: 6.0 #4.0
  use_wheels_motion_constraint: false
  traction_limit: 300.0 #300.0

Gap:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.95
   
  final_pose: 
    x: 3.5
    y: 0.0
    z: 0.95

  total_time: 3.0
  use_wheels_motion_constraint: false
  traction_limit: 400.0

SlopePlat:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.4
   
  final_pose: 
    x: 6.0
    y: 0.0
    z: 0.4

  total_time: 4.0
  use_wheels_motion_constraint: false
  traction_limit: 400.0

MultipleSlopes:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 6.0
    y: 0.0
    z: 0.5

  total_time: 4.0
  use_wheels_motion_constraint: false
  traction_limit: 400.0

SineLowFreq:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.6
   
  final_pose: 
    x: 8.0
    y: 0.0
    z: 0.6

  total_time: 8.0
  use_wheels_motion_constraint: false
  traction_limit: 30.0

SineHighFreq:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 4.0
    y: 0.0
    z: 0.5

  total_time: 4.0
  use_wheels_motion_constraint: false
  traction_limit: 30.0

Rough:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.4
   
  final_pose: 
    x: 4.0
    y: 0.0
    z: 0.9

  total_time: 3.5
  use_wheels_motion_constraint: false
  traction_limit: 30.0




