terrain: "SineHighFreq"
run_derivative_test: false
plot_trajectory: false
play_initialization: false
init_state_from_file: true  # 'true' if initial_pose for base is read from this file, 'false' if it is set by the current anymal state

constrain_initial_y_base: true

set_wheels_motion_cost: false
set_base_pitch_cost: false

use_non_holonomic_constraint: false

Flat:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.04445
   
  final_pose: 
    x: 2.0
    y: 0.0
    z: 0.04445

  total_time: 2.0
  traction_limit: 4000

Slope:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.04445
   
  final_pose: 
    x: 3.5
    y: 0.0
    z: 0.04445

  total_time: 5.0
  traction_limit: 4000

SineHighFreq:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.04445
   
  final_pose: 
    x: 4.0
    y: 0.0
    z: 0.04445

  total_time: 5.0
  traction_limit: 4000

SineLowFreq:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.04445
   
  final_pose: 
    x: 3.5
    y: 0.0
    z: 0.04445

  total_time: 4.0
  traction_limit: 4000

SlopePlat:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.04445
   
  final_pose: 
    x: 4.0
    y: 0.0
    z: 0.04445

  total_time: 4.0
  traction_limit: 4000








